let userNames = ['bishop','emmanuel','destiny','favour',
				 'enoch','goddy','bishop','desman',
				 'olamide','david','wwe','opp',
				 'prince','jumiloju','kayode','makinde',
				 'signIn','dp','favour','jumiloju'];
let surNames = ['bishop','emmanuel','destiny','favour',
				 'enoch','goddy','bishop','desman',
				 'olamide','david','wwe','opp',
				 'prince','jumiloju','kayode','makinde',
				 'signIn','dp','favour','jumiloju'];
let userAges = [2,3,4,5,6,7,8,9,4,3,5,8,9,0,7,4,3,3,5,6,7,8,9,10];

let randomName = Math.round(Math.random * userNames.length);
let randomsurName = Math.round(Math.random * surNames.length);
let randomAge = Math.round(Math.random * userAges.length);

let use  = [userList:[
 {id:1,name:randomName,surName:randomSurname,age:randomAge},
 {id:2,name:randomName,surName:randomSurname,age:randomAge},
 {id:3,name:randomName,surName:randomSurname,age:randomAge},
 {id:4,name:randomName,surName:randomSurname,age:randomAge},
 {id:5,name:randomName,surName:randomSurname,age:randomAge},
 {id:6,name:randomName,surName:randomSurname,age:randomAge},
 {id:7,name:randomName,surName:randomSurname,age:randomAge},
 {id:8,name:randomName,surName:randomSurname,age:randomAge},
 {id:9,name:randomName,surName:randomSurname,age:randomAge},
 {id:0,name:randomName,surName:randomSurname,age:randomAge},
 {id:11,name:randomName,surName:randomSurname,age:randomAge},
 {id:12,name:randomName,surName:randomSurname,age:randomAge},
 {id:13,name:randomName,surName:randomSurname,age:randomAge},
 {id:14,name:randomName,surName:randomSurname,age:randomAge},
 {id:15,name:randomName,surName:randomSurname,age:randomAge},
 {id:16,name:randomName,surName:randomSurname,age:randomAge},
 {id:17,name:randomName,surName:randomSurname,age:randomAge},
 {id:18,name:randomName,surName:randomSurname,age:randomAge},
 {id:19,name:randomName,surName:randomSurname,age:randomAge},
 {id:10,name:randomName,surName:randomSurname,age:randomAge},
 {id:21,name:randomName,surName:randomSurname,age:randomAge},
 {id:22,name:randomName,surName:randomSurname,age:randomAge},
 {id:23,name:randomName,surName:randomSurname,age:randomAge},
 {id:24,name:randomName,surName:randomSurname,age:randomAge},
 {id:25,name:randomName,surName:randomSurname,age:randomAge},
 {id:26,name:randomName,surName:randomSurname,age:randomAge},
 {id:27,name:randomName,surName:randomSurname,age:randomAge},
 {id:28,name:randomName,surName:randomSurname,age:randomAge},
 {id:29,name:randomName,surName:randomSurname,age:randomAge},
 {id:20,name:randomName,surName:randomSurname,age:randomAge},
 {id:31,name:randomName,surName:randomSurname,age:randomAge},
 {id:32,name:randomName,surName:randomSurname,age:randomAge},
 {id:33,name:randomName,surName:randomSurname,age:randomAge},
 {id:34,name:randomName,surName:randomSurname,age:randomAge},
 {id:35,name:randomName,surName:randomSurname,age:randomAge},
 {id:36,name:randomName,surName:randomSurname,age:randomAge},
 {id:37,name:randomName,surName:randomSurname,age:randomAge},
 {id:38,name:randomName,surName:randomSurname,age:randomAge},
 {id:39,name:randomName,surName:randomSurname,age:randomAge},
 {id:30,name:randomName,surName:randomSurname,age:randomAge},
 {id:41,name:randomName,surName:randomSurname,age:randomAge},
 {id:42,name:randomName,surName:randomSurname,age:randomAge},
 {id:43,name:randomName,surName:randomSurname,age:randomAge},
 {id:44,name:randomName,surName:randomSurname,age:randomAge},
 {id:45,name:randomName,surName:randomSurname,age:randomAge},
 {id:46,name:randomName,surName:randomSurname,age:randomAge},
 {id:47,name:randomName,surName:randomSurname,age:randomAge},
 {id:48,name:randomName,surName:randomSurname,age:randomAge},
 {id:49,name:randomName,surName:randomSurname,age:randomAge},
 {id:50,name:randomName,surName:randomSurname,age:randomAge},
 ]];
 let usersAllOfThem = JSON.stringify(use[0])